### ISSUE TITLE
Crashlytics and robovm

### ISSUE THREAD

**Issue by marcguilera** [BlueRiverInteractive/robovm-ios-bindings#173]
Has anyone been able to get working Crashlytics with the binging found on this repo? It seems pretty straight forward but for some reason my crashes are not reporting to Crashlytics. Is there any known issue?

**Comment by BlueRiverInteractive** [comment]
Crashlytics uses mach exception handling which isn't supported for RoboVM right now.

**Comment by BlueRiverInteractive** [comment]
I'll close this for now. If you want to use crashreporting with RoboVM, use Google Analytics or Flurry robopods: https://github.com/robovm/robovm-robopods

**Comment by alexitelman** [comment]
We'd also like to use Crashlytics with RoboVM, because we are using it in Android and would prefer to use the same tool in Android and iOS.
The error I'm getting when including the crashlytics frameworks (Fabric + Crashlytics) in robovm.xml :

```
[ERROR] Undefined symbols for architecture armv7:
[ERROR]   "std::get_terminate()", referenced from:
[ERROR]       _CLSExceptionCheckHandlers in Crashlytics(CLSException.o)
[ERROR]   "_gzopen", referenced from:
[ERROR]       -[CLSPackageReportOperation compressFile:] in Crashlytics(CLSPackageReportOperation.o)
[ERROR]   "_gzwrite", referenced from:
[ERROR]       ___42-[CLSPackageReportOperation compressFile:]_block_invoke in Crashlytics(CLSPackageReportOperation.o)
[ERROR]   "_gzclose", referenced from:
[ERROR]       -[CLSPackageReportOperation compressFile:] in Crashlytics(CLSPackageReportOperation.o)
[ERROR] ld: symbol(s) not found for architecture armv7
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
```
the gz errors are related to the fact that it needs to link agains libz.dylib but I can't seem to find a way to add it to robovm.xml.. If I add it under libs it tries to look for it in the InteeliJ folder, but it's not there... and adding it under frameworks also doesn't work.

what is the std::get_terminate() error?

Will this be supported anytime soon?
