### ISSUE TITLE
Google Analytics missing sample & possibly not working

### ISSUE THREAD

**Issue by jpancik** [BlueRiverInteractive/robovm-ios-bindings#48]
Hello,

I have a problem with google analytics. My tracking code is not sending any data (tested with realtime and also checked on the next day). It worked in previous versions and I have updated my libs properly.

As there is no sample to check against, I will post my code here and if I'm doing something wrong please point it out. Maybe somebody could share their working tracking code?

Thanks.

```Java
public class IOSAnalyticsClient implements GoogleAnalyticsClient {
    private String id;

    private GAIDefaultTracker tracker;
    
    public IOSAnalyticsClient(String id) {
        this.id = id;
    }
    
    @Override
    public void startSession() {
        GAI.getSharedInstance().setDryRun(false);
        GAI.getSharedInstance().setDispatchInterval(20.0);
        
        tracker = GAI.getSharedInstance().getTracker(id);
    }

    @Override
    public void stopSession() {
        try {
            tracker.dispose();
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

    @Override
    public void trackEvent(String category, String action, String label, long value) {
        tracker.send(GAIDictionaryBuilder.createEvent(category, action, label, NSNumber.valueOf(value)).build());
    }

    @Override
    public void trackPageView(String name) {
        tracker.set("kGAIScreenName", name);
        tracker.send(GAIDictionaryBuilder.createAppView().build());
    }

    @Override
    public void trackTiming(String category, long timeInMilliseconds, String name, String label) {
        tracker.send(GAIDictionaryBuilder.createTiming(category, NSNumber.valueOf(timeInMilliseconds), name, label).build());
    }

    @Override
    public void trackException(String description, Throwable t, boolean fatal) {
        tracker.send(GAIDictionaryBuilder.createException(description, fatal).build());
    }

    @Override
    public void dispatch() {
        //System.out.println("dispatching");
        GAI.getSharedInstance().dispatch();
    }
}
```

**Comment by Don-F** [comment]
Hey guys, sorry to unearth this old discussion but I am currently having the exact same problem.
Here is what I've tried:
- Adding the analytics jar as a library: my ios game runs fine but when triggering analytics, I am having the  "Class org.robovm.apple.foundation.NSObject does not implement the requested interface org.robovm.bindings.googleanalytics.GAITracker" error

- Adding the whole analytics project, then linking to it from my main project's build path: I cannot run my game anymore, it doesn't compile. I am having the error : "error: package org.robovm.bindings.googleanalytics does not exist" when launching with gradle from a terminal command line. What is weird is that in Eclipse, I can link MANUALLY the analytics project from my main project, everything looks ok, but when I right click my ios project then Refresh All, it automatically removes the analytics project from the build path.

I guess it comes from a gradle or robovm seting or property but I have no idea which one.
Anybody has an idea?
Otherwise, anybody could point me to a .jar for analytics? That would solve my problem too.

**Comment by AgrarPirat** [comment]
@marcinjakubowski, thank you for the fix. 
I've added it and the app compiles and runs just fine. The only problem is that Google Analytics does not receive any events.
I suppose it's because the Google Analytics native library (libGoogleAnalyticsServices.a) is still missing. Just a guess though, but how can it be added to the project? Whats the right way to ensure it's getting picked up by roboVM? Any advice how to get it running is welcome.
Thank you.

**Comment by voidstarfire** [comment]
I'm having the same issue, using LibGDX jar. Still not working :-1:

**Comment by perchi** [comment]
Me too! :-1:

**Comment by zfmbek** [comment]
Can anyone share the corect *.jar file of @marcinjakubowski fixed version? 

thanks in advance

**Comment by zfmbek** [comment]
@Don-F Can anyone share the corect *.jar?

**Comment by BleedObsidian** [comment]
Here is the compiled and working jar containing @marcinjakubowski fix.
Download (Dropbox): https://www.dropbox.com/s/n6p7qrns5qetia7/Google-Analytics-Binding_Fix.jar?dl=0

**Comment by zfmbek** [comment]
@BleedObsidian Thank you

**Comment by rotter** [comment]
Has anyone managed to use Google Analytics on current RoboVM version? Since
a couple RoboVM updates it doesnt run anymore for me (crashes game on
start).

**Comment by BlueRiverInteractive** [comment]
The Google Analytics bindings are deprecated. Please use the new iOS RoboPod for Google Analytics: 
https://github.com/robovm/robovm-robopods.
Essentially you only need to add a maven or Gradle dependency to your robovm project, like: 
```
org.robovm:robopods-google-analytics-ios:1.0.0-SNAPSHOT
```
or 
```
<dependency>
   <groupId>org.robovm</groupId>
   <artifactId>robopods-google-analytics-ios</artifactId>
   <version>1.0.0-SNAPSHOT</version>
</dependency>
```

If you find any issues with the robopods, please post in the respective repository. Thanks
